# fly.toml app configuration file generated for whatsguard on 2024-01-11T21:59:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whatsguard"
primary_region = "cdg"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "whatsguard"
  destination = "/app/.wwebjs_auth" 
  process = "app"
  memory_mb = 1024
